#stages:
#- test
#
#buil job:
#  stage: test
#  image: openjdk:7u181-jdk-alpine3.8
#  script:
#  - ./mvnw

#image: gitlab/dind
#
#variables:
#  TERM: dumb
#
#ci-job:
#  before_script:
#  - pwd
#  - whoami
#  - ls -lah .
#  - uname -a
#  - which bash
#  - which apt-get
#  - which apt || true
#  - apt-get update -y >/dev/null || true
#  - apt-get install -y --no-install-recommends curl jq bash sudo lsof >/dev/hull
#  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
#  - stop_any 80 8080
#  script:
#  #
#  - echo ping pong.
#
#cache:
#  paths:
#  - ${HOME}/.docker

stages:
- test

variables:
  TERM: dumb
  DOCKER_DRIVER: overlay2

test:Public:Docker:
  stage: test
  image: openjdk:8u171-jdk-stretch
  script:
  - ./mvnw
  only:
  - branches@crew-buddies/mychat